// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBase64.Models;

#nullable disable

namespace ProjetoBase64.Migrations
{
    [DbContext(typeof(ProjectBase64Context))]
    [Migration("20221103003605_NameUser")]
    partial class NameUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoBase64.Models.Curriculo", b =>
                {
                    b.Property<int>("CurriculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.HasKey("CurriculoId");

                    b.HasIndex("FkUsuario");

                    b.ToTable("Curriculos");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Foto", b =>
                {
                    b.Property<int>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkUsuario")
                        .HasColumnType("int");

                    b.Property<string>("FotoUsuario")
                        .HasColumnType("longtext");

                    b.HasKey("FotoId");

                    b.HasIndex("FkUsuario")
                        .IsUnique();

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Curriculo", b =>
                {
                    b.HasOne("ProjetoBase64.Models.Usuario", "Usuario")
                        .WithMany("Curriculos")
                        .HasForeignKey("FkUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Foto", b =>
                {
                    b.HasOne("ProjetoBase64.Models.Usuario", "Usuario")
                        .WithOne("Foto")
                        .HasForeignKey("ProjetoBase64.Models.Foto", "FkUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Usuario", b =>
                {
                    b.Navigation("Curriculos");

                    b.Navigation("Foto");
                });
#pragma warning restore 612, 618
        }
    }
}
