// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBase64.Models;

#nullable disable

namespace ProjetoBase64.Migrations
{
    [DbContext(typeof(ProjectBase64Context))]
    [Migration("20221104022951_NomeCurriculo")]
    partial class NomeCurriculo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoBase64.Models.Curriculo", b =>
                {
                    b.Property<int>("CurriculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("CurriculoId");

                    b.ToTable("Curriculos");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Foto", b =>
                {
                    b.Property<int>("FotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkCurriculo")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.HasKey("FotoId");

                    b.HasIndex("FkCurriculo");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkCurrilo")
                        .HasColumnType("int");

                    b.Property<int?>("FotoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("FkCurrilo");

                    b.HasIndex("FotoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Foto", b =>
                {
                    b.HasOne("ProjetoBase64.Models.Curriculo", "Curriculo")
                        .WithMany("Fotos")
                        .HasForeignKey("FkCurriculo");

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Usuario", b =>
                {
                    b.HasOne("ProjetoBase64.Models.Curriculo", "Curriculo")
                        .WithMany()
                        .HasForeignKey("FkCurrilo");

                    b.HasOne("ProjetoBase64.Models.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId");

                    b.Navigation("Curriculo");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("ProjetoBase64.Models.Curriculo", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
